apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-12-13T16:17:44Z"
  name: carts-canary
  resourceVersion: "1265549"
  selfLink: /api/v1/namespaces/sockshop-production/services/carts
  uid: 182aa5ab-1dc4-11ea-9f50-42010a800178
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: carts
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
